# Team Members

# Abhinav Veeragandham - G01515455
# Pranav Vangavety - G01511443
# Charan Sri Sai Devalla - G01504177
# Bhogeswara Pathakamudi - G01507114
# Durga Shankar Kondaveeti - G01510533

apiVersion: v1
kind: Service
metadata:
  name: survey
spec:
  selector:
    app: survey
  type: NodePort
  ports:

    - port: 80         
      targetPort: 80    
      nodePort: 30008   
