apiVersion: v1
kind: Service
metadata:
  name: survey
spec:
  selector:
    app: survey
  type: NodePort
  ports:

    - port: 80         
      targetPort: 80    
      nodePort: 30008   